###服务端口号(本身是一个web项目)
server:
  port: 8081
###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
    application:
        name: app-item
    zipkin:
        base-url: http://localhost:9411

   # mysql 属性配置
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
      driver-class-name: com.mysql.cj.jdbc.Driver       #配置MySQL的驱动程序类,mysql8特殊配置
      url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: tiger
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
           defaultZone: http://127.0.0.1:8100/eureka
###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
###是否需要从eureka上检索服务
    fetch-registry: true

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.king.soft.entity
